CREATE TABLE pota4187.Artist (
	ID				SERIAL,
	Name			VARCHAR(20)			NOT NULL,
	Surname		VARCHAR(20),
	PRIMARY KEY (ID)	 
);

CREATE TABLE pota4187.Card (
	Name			VARCHAR(20)			NOT NULL,
	Type			VARCHAR(25)			NOT NULL,
	Cost			INTEGER		CONSTRAINT positiveCost CHECK (Cost >= 0) DEFAULT 0,
	CText			VARCHAR(210),
	Color			CHAR(5) 				NOT NULL DEFAULT 'C',
	PRIMARY KEY (Name)
);

CREATE TABLE pota4187.Painting (
	Name			VARCHAR(25)			NOT NULL,
	ArtistID		INTEGER 				NOT NULL,
	PRIMARY KEY (Name),
	FOREIGN KEY (ArtistID) REFERENCES Artist ON DELETE CASCADE
);
CREATE TABLE pota4187.CSET (
	Code			VARCHAR(3)			NOT NULL,
	CAmount		INTEGER				NOT NULL,
	Year			INTEGER CONSTRAINT afterGameCreationYear CHECK (Year >= 1993),
	Name			VARCHAR(30),
	PRIMARY KEY (Code)
);	

CREATE TABLE pota4187.Specimen (
	Nr				INTEGER			NOT NULL CONSTRAINT nonNegativeCardNr CHECK (Nr >= 0),
	Painting		VARCHAR(25),
	SetCode		VARCHAR(3)		NOT NULL,
	FText			VARCHAR(125),
	Name			VARCHAR(20)  	NOT NULL,
	PRIMARY KEY (Nr, SetCode),
	FOREIGN KEY (Painting) REFERENCES pota4187.Painting ON DELETE CASCADE,
	FOREIGN KEY (Name) REFERENCES pota4187.Card ON DELETE CASCADE,
	FOREIGN KEY (SetCode) REFERENCES pota4187.CSET ON DELETE CASCADE
);
