CREATE TABLE Artist (
	ID				INTEGER				NOT NULL,
	Name			VARCHAR(20)			NOT NULL,
	Surname		VARCHAR(20),
	PRIMARY KEY (ID)	 
);

CREATE TABLE CSET (
	Code			VARCHAR(3)			NOT NULL,
	CAmount		INTEGER				NOT NULL,
	Year			INTEGER CHECK (Year >= 1993),
	SpecimenNr	INTEGER,
	Name			VARCHAR(30),
	PRIMARY KEY (Code)
);	

CREATE TABLE Card (
	Name			VARCHAR(20)		NOT NULL,
	Type			VARCHAR(25)		NOT NULL,
	Cost			INTEGER		CHECK (Cost >= 0),
	CText			VARCHAR(210),
	Color			CHAR(5) 			NOT NULL DEFAULT 'C',
	PRIMARY KEY (Name)
);

CREATE TABLE Painting (
	Name			VARCHAR(25)		NOT NULL,
	ArtistID		INTEGER 			NOT NULL,
	PRIMARY KEY (Name),
	FOREIGN KEY (ArtistID) REFERENCES Artist ON DELETE CASCADE
);

CREATE TABLE Specimen (
	Nr				INTEGER			NOT NULL CHECK (Nr >= 0),
	Painting		VARCHAR(25),
	Set			VARCHAR(3)			NOT NULL,
	FText			VARCHAR(125),
	Name			VARCHAR(20)  	NOT NULL,
	PRIMARY KEY (Nr, Set),
	FOREIGN KEY (Painting) REFERENCES Painting ON DELETE CASCADE,
	FOREIGN KEY (Set) REFERENCES CSET ON DELETE CASCADE,
	FOREIGN KEY (Name) REFERENCES Card ON DELETE CASCADE
);
	

