CREATE TABLE Artist (
	ID		INTEGER		NOT NULL,
	Name		VARCHAR(20)	NOT NULL,
	Surname		VARCHAR(20)
	PRIMARY KEY (ID));
CREATE TABLE Painting (
	Name		VARCHAR(25)	NOT NULL,
	ArtistID	INTEGER,
	PRIMARY KEY (Name));
--	CONSTRAINT IArtist FOREIGN KEY (Artist) REFERENCES
CREATE TABLE Specimen (
	Nr		INTEGER		NOT NULL CHECK (Nr >= 0),
	Painting	VARCHAR(25),
	Set		CHAR(3)		NOT NULL,
	FText		VARCHAR(100),
	Name		VARCHAR(20));
	PRIMARY KEY (Nr, Set));
--	CONSTRAINT IPainting FOREIGN KEY (Painting) REFERENCES
--	CONSTRAINT ICSET FOREIGN KEY (CSET) REFERENCES
--	CONSTRAINT ICard FOREIGN KEY (Name) REFERENCES
CREATE TABLE Card (
	Name		VARCHAR(20)	NOT NULL,
	Type		VARCHAR(15),
	Cost		INTEGER		CHECK (Cost >= 0),
	CText		VARCHAR(100),
	Color		CHAR(1)
	CONSTRAINT Colors CHECK (Color IN ('W', 'U', 'B', 'R', 'G', 'C')),
	PRIMARY KEY (Name));
CREATE TABLE CSET (
	Code		CHAR(3)		NOT NULL,
	CAmount		INTEGER,
	Year		DATE,
	SpecimenNr	INTEGER,
	Name		VARCHAR(20)
	PRIMARY KEY (Code)).
